ENTESB-10331: Added a exclusion to enforce javax.ws.rs to be ignored …
jboss-fuse/fuse-build-yaml pull request #37
Opened 2019-03-22 10:48 UTC by orpiske

Tries to prevent PME from manipulating javax.ws.rs in CXF, which is causing trouble due to invalid OSGI manifests.

2019-03-22 10:52 UTC, oscerd approved these changes

2019-04-01 16:15 UTC, cunningt requested changes
I think you also have to remove the dependencyOverride on javax.ws.rs.

2019-04-01 16:20 UTC, orpiske commented
> I think you also have to remove the dependencyOverride on javax.ws.rs.

Thanks. I've just pushed an updated commit with that override removed.

2019-04-08 16:28 UTC, djcoleman approved these changes

2019-04-08 16:29 UTC, merged